### ISSUE TITLE
Route function should include nonce

### ISSUE THREAD

**Issue by jboetticher** [glacislabs/v1-core#10]
GlacisRouter `route` function should include `nonce` as an output so that smart contracts can programmatically retry instead of relying on external tools to cache nonce.

```solidity
   function route(
        uint256 chainId,
        bytes32 to,
        bytes memory payload,
        uint8[] memory gmps,
        uint256[] memory fees,
        address refundAddress,
        bool retriable
    ) public payable virtual returns (bytes32, uint256); 
```

**Comment by gusjavaz** [comment]
Agree!

**Comment by jboetticher** [comment]
Addressing in https://github.com/glacislabs/v1-core/pull/11

**Comment by jboetticher** [comment]
Addressed with https://github.com/glacislabs/v1-core/pull/11
