### ISSUE TITLE
Glacis v1 using very old non maintained version of LayerZero

### ISSUE THREAD

**Issue by bholcomb8** [glacislabs/v1-core#27]
This project not only uses v1, but is also referencing very old non maintained contracts from a non maintained repo. LayerZero v2 offers much more robust security and performance and makes up the bulk of messages on LayerZero at this point in time. You can find the latest code in our npm package: https://www.npmjs.com/package/@layerzerolabs/lz-evm-oapp-v2 and docs here: https://docs.layerzero.network/v2/developers/evm/overview

Though our endpoints are immutable (including v1) there is no guarantee we will keep the examples repo intact and there have been many upgrades to security and performance in newer version of LayerZero.

**Comment by gusjavaz** [comment]
Thanks for your feedback @bholcomb8! We are indeed very aware of LZ's v2 new features and improvements and we are planning to add V2 support to Glacis in the short term.

**Comment by gusjavaz** [comment]
LZ Adapter Replaced with LZ V2 support

**Comment by bholcomb8** [comment]
Awesome!
